<template>
  <main class="success-page safe-top"><section class="status-panel"><span class="brand">b.</span><div v-if="loading" class="status-copy" role="status"><div class="status-icon pending">…</div><h1>Checking payment</h1><p>We are confirming your payment with our secure provider.</p></div><div v-else-if="error" class="status-copy" role="alert"><div class="status-icon failed">!</div><h1>We cannot verify this order</h1><p>{{ error }}</p></div><div v-else-if="isPaid" class="status-copy"><div class="status-icon paid">✓</div><span class="eyebrow">PAYMENT CONFIRMED</span><h1>Your find is yours</h1><p>Order {{ order.order_number }} is confirmed. We will update you when it is on the way.</p></div><div v-else class="status-copy"><div class="status-icon pending">⌛</div><span class="eyebrow">{{ order.status==='cancelled'?'PAYMENT WINDOW ENDED':'ORDER SAVED' }}</span><h1>{{ order.status==='cancelled'?'Payment was not completed':'Payment is processing' }}</h1><p>{{ order.status==='cancelled'?'The reserved stock has been released. Add the items to your cart again when you are ready.':'This may take a moment. Your order page will show the latest status.' }}</p></div><div class="actions"><router-link v-if="order" :to="`/my-orders/${order.id}`">View order</router-link><router-link to="/">Continue shopping</router-link></div></section></main>
</template>
<script setup>
import {computed,onMounted,ref} from 'vue';import {useRoute} from 'vue-router';import {getMyOrder} from '../api'
const route=useRoute(),order=ref(null),loading=ref(true),error=ref('');const isPaid=computed(()=>['paid','shipped','completed'].includes(order.value?.status)||order.value?.payment_status==='paid')
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function load(){const id=route.query.order_id||sessionStorage.getItem('pending_order_id');if(!id){error.value='This link does not include an order number.';loading.value=false;return}try{for(let n=0;n<3;n++){order.value=(await getMyOrder(id)).data;if(isPaid.value)break;if(n<2)await wait(1500)}if(isPaid.value)sessionStorage.removeItem('pending_order_id')}catch(e){error.value=e.response?.data?.detail||'The order could not be loaded.'}finally{loading.value=false}}onMounted(load)
</script>
<style scoped>
.success-page{min-height:100vh;display:grid;place-items:center;background:#f4f1e8;color:#173f34;padding:1.25rem}.status-panel{position:relative;width:min(100%,32rem);overflow:hidden;border-radius:2rem;background:#fffdf7;padding:2.2rem 1.5rem;text-align:center;box-shadow:0 20px 55px rgba(23,63,52,.1)}.brand{position:absolute;left:1.25rem;top:1rem;font:700 2rem Georgia,serif}.status-icon{width:5rem;height:5rem;display:grid;place-items:center;margin:1rem auto;border-radius:50%;font-size:2rem;font-weight:900}.status-icon.paid{background:#dff263}.status-icon.pending{background:#e4e9e3}.status-icon.failed{background:#f5d9d3;color:#9d3434}.eyebrow{font-size:.65rem;font-weight:900;letter-spacing:.18em;color:#6d7b75}.status-copy h1{margin:.45rem 0;font:700 2rem Georgia,serif}.status-copy p{max-width:24rem;margin:.6rem auto 1.5rem;color:#65726d;line-height:1.55}.actions{display:grid;gap:.65rem}.actions a{border:1px solid #173f34;border-radius:999px;padding:.85rem;color:#173f34;font-weight:900}.actions a:first-child{background:#173f34;color:#e1f56c}
</style>
